# Generated by Django 5.0.1 on 2024-01-10 12:45

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_resource_created_at_resource_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="api.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Discussions",
                "ordering": ["-created_at"],
            },
        ),
    ]
